/**
 * TypeScript definitions for Razorpay Standard Checkout SDK (checkout.js)
 */

export interface RazorpayCheckoutResponse {
  razorpay_payment_id: string;
  razorpay_order_id: string;
  razorpay_signature: string;
}

export interface RazorpayCheckoutOptions {
  key: string;
  amount: number; // Amount in smallest currency unit (e.g. paise for INR)
  currency: string;
  name: string;
  description?: string;
  image?: string;
  order_id: string; // The order_... identifier generated by the backend
  handler: (response: RazorpayCheckoutResponse) => void;
  modal?: {
    ondismiss?: () => void;
    escape?: boolean;
    backdropclose?: boolean;
  };
  prefill?: {
    name?: string;
    email?: string;
    contact?: string;
  };
  notes?: Record<string, string>;
  theme?: {
    color?: string;
    hide_topbar?: boolean;
  };
}

export interface RazorpayInstance {
  open(): void;
  close?(): void;
  on?(event: string, callback: (...args: unknown[]) => void): void;
}

declare global {
  interface Window {
    Razorpay?: new (options: RazorpayCheckoutOptions) => RazorpayInstance;
  }
}

export {};
